# NumPy Arrays

In [1]:
import numpy as np

In [37]:
arr = np.arange(0,11)

In [38]:
arr 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [40]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [41]:
arr / arr

C:\Users\DELL\AppData\Local\Temp\ipykernel_10944\3001117470.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [42]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [43]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [44]:
np.max(arr)

10

# Create an array of five zeros

In [6]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

# Create an array of 10 ones

In [7]:
np.ones(10)


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Create an array of 10 fives

In [8]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

# Create an array of integers  from 1 to100

In [11]:
arr = np.arange(1,101)
arr

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

# Create an array of even integers between 10 to 50

In [13]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

# Create a 3X3 matrix with values ranging from 0 to 8

In [32]:
arr = np.arange(0,9)
arr.reshape(3,3)


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [33]:
arr.reshape(1,-1)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [34]:
arr.reshape(-1,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

# Create a 3X3 idenntity matrix

In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Use NumPy to generate a random number between 0 and 1

In [17]:
np.random.rand(1)

array([0.05498844])

In [45]:
np.random.randn(25)

array([-0.6347761 , -0.84530981, -1.23058497,  0.00998438, -0.66711053,
       -0.74849629, -0.27631781, -0.99483341,  0.12300857,  1.39027926,
        1.91028245,  0.07484215, -0.60090087,  0.81821492,  0.7137722 ,
        1.18200807, -1.16608014, -0.54077428,  0.70418929,  0.82287256,
       -0.28321764,  0.18464768,  0.24573233, -0.03993232, -0.22120425])

# Numpy Indexing and Selection

In [23]:
mat = np.arange(1,51).reshape(5,10)
mat

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48, 49, 50]])

In [46]:
np.arange(1,51).reshape(10,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [48]:
np.arange(1,51).reshape(5,10)/50

array([[0.02, 0.04, 0.06, 0.08, 0.1 , 0.12, 0.14, 0.16, 0.18, 0.2 ],
       [0.22, 0.24, 0.26, 0.28, 0.3 , 0.32, 0.34, 0.36, 0.38, 0.4 ],
       [0.42, 0.44, 0.46, 0.48, 0.5 , 0.52, 0.54, 0.56, 0.58, 0.6 ],
       [0.62, 0.64, 0.66, 0.68, 0.7 , 0.72, 0.74, 0.76, 0.78, 0.8 ],
       [0.82, 0.84, 0.86, 0.88, 0.9 , 0.92, 0.94, 0.96, 0.98, 1.  ]])

In [49]:
mat[ : ,: 1]

array([[ 1],
       [11],
       [21],
       [31],
       [41]])

In [50]:
mat[0:1, :]

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [25]:
mat[ : , 6:10]

array([[ 7,  8,  9, 10],
       [17, 18, 19, 20],
       [27, 28, 29, 30],
       [37, 38, 39, 40],
       [47, 48, 49, 50]])

In [26]:
mat[0:3,0:3]

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23]])

In [27]:
mat[0][9]

10

# Get the sum of all the values in mat

In [28]:
mat.sum()

1275

# Get the standard deviation of the values in mat

In [30]:
np.std(mat)

14.430869689661812

In [51]:
mat.sum(axis=0)

array([105, 110, 115, 120, 125, 130, 135, 140, 145, 150])